baseURL = "https://barcelona-declaration.org"
languageCode = "en-us"
title = "Barcelona Declaration - Working Groups"
contentdir = "content"
theme = "beautifulhugo"
enableRobotsTXT = true

[params]
  selfHosted = true
  favicon = "/favicon.jpg"

[params.author]
    mastodon = "mastodon.social/@BarcelonaDORI"
    bluesky = "barcelonadori.bsky.social"
    linkedin = "barcelona-declaration/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "roadmap"  
    name = "Working groups"
    url = "roadmap_parent/"
    weight = 2

[[menu.main]]
    name = "Working groups"
    url = "working_groups/"
    parent = "roadmap"
    weight = 1
    